
services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env

  django-docker:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
   postgres_data: