# Generated by Django 5.1.6 on 2025-02-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code_created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
