# Generated by Django 5.1.6 on 2025-02-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_forgot_password_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
